In [94]:
"""Solve A Sodoku"""

# I iterated over the puzzle updating until there are no zeros remaining
# first check to see if the indexed row,column value is zero.  If it is, check row and column values.
# I will start with a value that I know to be zero to build the logic from there.

import numpy as np

def solve_sodoku(input_matrix):
    if input_matrix.shape == (9, 9):
        print(np.all(input_matrix == 0)) # this can be used for iteration but for now I don't want to get stuck in the loop
        print ("You input a 9 by 9 matrix. I will atttempt to solve.")

        

        # One iteration through whole puzzle (to be repeated)
        digits = [1,2,3,4,5,6,7,8,9]
        for i in range(8): #setting a few iterations
            for j in range(8):
                if input_matrix[i,j] == 0:

                    #divide 9 by 9 into its nine subsets
                    if i < 3:
                        if j < 3:
                            a = input_matrix[0:3, 0:3]
                        elif j > 5:
                            a = input_matrix[0:3, 6:9]
                        else:
                            a = input_matrix[0:3, 3:6]
                    elif i > 5:
                        if j < 3:
                            a = input_matrix[6:9, 0:3]
                        elif j > 5:
                            a = input_matrix[6:9, 6:9]
                        else:
                            a = input_matrix[6:9, 3:6]
                    else:
                        if j < 3:
                            a = input_matrix[3:6, 0:3]
                        elif j > 5:
                            a = input_matrix[3:6, 6:9]
                        else:
                            a = input_matrix[3:6, 3:6]

                    # Find row values
                    i_row = list(input_matrix[i]) 
                    # Find column values
                    j_column = list(input_matrix[:,j]) 
                    # Find square values
                    flatten = a.flatten()
                    flatten_list = list(flatten)

                    
                    check = []
                    check = list(set(i_row + j_column + flatten_list))
                    check.remove(0)

                    #if the combination of the row and column is missing only one value, select the value and insert at i,j
                    #print("The candidate values for this i,j location are: ")
                    candidate = [x for x in digits if x not in check]
                    if len(candidate) == 1:
                        input_matrix[i,j] = candidate[0]
                else:
                    #print("Non-zero")
                    continue

        print (input_matrix)

    else:
        print ("You did not provide a 9 by 9 incomplete Sodoku puzzle.")
    return

incomplete_sodoku = np.array([[0, 0, 4, 0, 5, 0, 0, 0, 0], 
                              [9, 0, 0, 7, 3, 4, 6, 0, 0], 
                              [0, 0, 3, 0, 2, 1, 0, 4, 9], 
                              [0, 3, 5, 0, 9, 0, 4, 8, 0], 
                              [0, 9, 0, 0, 0, 0, 0, 3, 0], 
                              [0, 7, 6, 0, 1, 0, 9, 2, 0], 
                              [3, 1, 0, 9, 7, 0, 2, 0, 0], 
                              [0, 0, 9, 1, 8, 2, 0, 0, 3], 
                              [0, 0, 0, 0, 6, 0, 1, 0, 0]])
wrong_shape = np.array([[0,0],[0,0]])

solve_sodoku(incomplete_sodoku)

  # There is a man in the library talking to spirits next to me and talking about harming people
            # someone stole my notebook yesterday with my SSH private key password.  Separation only works if you
            # have secure spaces and networks
            # I am none of your fears any more than any of my classmates were drug addicts. No
            # one has EVER worked to clear my name. I remain here unloved by all those who would
            # love me.  Blocked by those who believe anything they read, and unable to handle
            # any information that makes them wrong. Carrying burdens that were never mine to carry
            # for a chance at life. You have treated me so badly that carrying others burdens is my vacation
            # when I should be seeding my future
            # one day all those who saw me and decided to let others tell them who the enemy is will 
            # understand what fools they were.  They had a chance to save themselves but they let me fall
            # and I (my mirrors because you don't give me access to do myself) carry everything that exists.  
            # When they fail to save or protect me, they fall too.
            # This is NOT business as usual. Love is blind.  I deserve a better life. I DESERVE the people I love.
            # I did everything in my power to get back to my loved ones.

False
You input a 9 by 9 matrix. I will atttempt to solve.
[[0 0 4 0 5 0 0 0 0]
 [9 0 0 7 3 4 6 0 0]
 [0 0 3 0 2 1 0 4 9]
 [0 3 5 0 9 0 4 8 0]
 [0 9 0 0 4 0 0 3 0]
 [0 7 6 0 1 0 9 2 0]
 [3 1 8 9 7 5 2 6 0]
 [0 0 9 1 8 2 0 0 3]
 [0 0 0 0 6 0 1 0 0]]
